### ISSUE TITLE
SoundCloud channel

### ISSUE THREAD

**Issue by DakotaNelson** [DakotaNelson/sneaky-creeper#11]
A SoundCloud channel module to transfer data encoded in sound would be awesome.

**Comment by byronwasti** [comment]
The soundCloud channel is actually finished on my branch. I haven't implemented steganography yet, nor have I fixed it to work with the main file. When I get those completed it should be completely ready.

**Comment by DakotaNelson** [comment]
Awesome!

**Comment by DakotaNelson** [comment]
@byronwasti what's the status on this?

**Comment by byronwasti** [comment]
Everything is implemented and works. I just have to go through and make sure it works smoothly with the rest of the framework.

**Comment by DakotaNelson** [comment]
Awesome, sounds great. Set up a PR when you're ready - I'm excited to see this thing in action.

**Comment by DakotaNelson** [comment]
Closed by PR #26.
