### ISSUE TITLE
Interactive Binary Crafting Mode

### ISSUE THREAD

**Issue by ManickYoj** [DakotaNelson/sneaky-creeper#12]
Sneaky-creeper should have an interactive mode (which should be really easy to start) which allows a user to set up their encryption scheme(s), channel(s), config, and target system(s) and outputs a compiled binary file for the target system.

**Comment by DakotaNelson** [comment]
Interactive mode - somewhat like recon-ng and/or metasploit. I like it.

So, the question arises... do we keep both modes, or switch entirely to this interactive mode? I can see arguments both ways. Maybe start with both and deprecate one if it isn't used?

**Comment by ManickYoj** [comment]
IMHO, the latter - start with both.

**Comment by DakotaNelson** [comment]
No longer relevant due to PR #61.
