### ISSUE TITLE
Compile to a final binary

### ISSUE THREAD

**Issue by DakotaNelson** [DakotaNelson/sneaky-creeper#13]
Sneaky-creeper should be compiled to a binary (rather, several binaries) so that it can be run on non-python-enabled systems, and without installing libraries.

[This SO question](http://stackoverflow.com/questions/12339671/how-to-compile-python-script-to-binary-executable) has some ideas.

**Comment by DakotaNelson** [comment]
The Veil framework does compilation. [This](https://github.com/Veil-Framework/Veil-Evasion/blob/24b9b48fab12f3af21e2fb8273b6ff67eb89c4dc/modules/common/supportfiles.py#L18-L138) should prove very helpful.

**Comment by davinerd** [comment]
Sorry @DakotaNelson , I was not able to find a way to compile sneaky-creeper thorught Veil. Do you have any hint?

Thanks

**Comment by DakotaNelson** [comment]
Since refactoring sneaky-creeper as a library, this is less of an issue.

I'm closing for now.
