### ISSUE TITLE
Twitter module retrieving user timeline while sending

### ISSUE THREAD

**Issue by DakotaNelson** [DakotaNelson/sneaky-creeper#15]
In [the Twitter module's send function](https://github.com/DakotaNelson/sneaky-creeper/blob/03f58520b7a856f9a42525f948508b94b3fdf7ff/channels/twitter.py#L33), it retrieves the user's timeline. Does it need to?

**Comment by buttegab** [comment]
It is unnecessary, I removed it.

**Comment by DakotaNelson** [comment]
Closed by PR #30.
