### ISSUE TITLE
Pass Params to Decode from Receiver

### ISSUE THREAD

**Issue by ManickYoj** [DakotaNelson/sneaky-creeper#20]

**Comment by ManickYoj** [comment]
Until PR #19 , decode did not take parameters as an argument, and thus threw an error claiming required parameters were not inputted if the decoder required params.

The above issue was resolved by PR #19, but the receiver does not pass the params argument when calling decode. It seems it should. Comments, (esp. @DakotaNelson )?

**Comment by DakotaNelson** [comment]
Yep, it should. This is resolved in 8e793b59f5fd033faf586f4b84e0d61c89593ed5, I believe.

**Comment by ManickYoj** [comment]
Thanks for nabbing that.
