### ISSUE TITLE
File Read `Print` Statements Contaminate Output

### ISSUE THREAD

**Issue by ManickYoj** [DakotaNelson/sneaky-creeper#37]
When reading a file, the file reading channel outputs some basic status information. However, this causes an issue that, if the output from a file read is piped to another command, the printed lines will come along for the ride.

For example, if the file 'input' contains the string "testing" and the following command is run:

'./screep receive -c file -e identity -p '{"file": {"filename": "input"}}' | ./screep send -c file -e identity -p '{"file": {"filename":"output"}}'

Then the resulting output in the file "output" is:
Reading data from input...
Done.
testing

Obviously, this example is contrived, but Sneaky-Creeper has an unlooked for utility in that it can be used now to encode arbitrary data (for example by piping a plaintext file read through a file write with rsa encoding). We may want to resolve this issue, and keep future outputs clean so that we can extend sneaky-feature's toolset as a general encoder/decoder with a large variety of possible channels.

**Comment by DakotaNelson** [comment]
This is a really good point.

I think a `--verbose` flag is the answer here.
