### ISSUE TITLE
Manage dependencies from within the framework

### ISSUE THREAD

**Issue by DakotaNelson** [DakotaNelson/sneaky-creeper#39]
The following will install Twython:

``` python
import pip
pip.main(['install','twython','-q'])
# the -q makes it quiet - no verbose progress bars
```

This means we can just require that any modules list its dependencies, and have the framework install them automatically.

How cool is that?

**Comment by ManickYoj** [comment]
This is excellent. I had no idea this was an option.

Also, it looks like you may have resolved this? Should this issue be closed?

**Comment by DakotaNelson** [comment]
It's not quite there. I'll have a PR in sometime today.

Yeah, I didn't either. It's weird that this isn't more common.

**Comment by DakotaNelson** [comment]
Okay, now I know why this isn't more common. It's a giant pain in the ass and python doesn't like it very much.

It works for now, we'll see if this is maintainable in the long term. I think it will be, but it'll definitely be more work upfront to get the framework set up right.

**Comment by davinerd** [comment]
Why not leave the dependencies to pip ? The requirements.txt file works great, and everything is delegated to pip and the user. Don't think `pip install -r requirements.txt` is too hard to type.

Simple, fast, effective, no messing around with the project core.

Just my 2c.

**Comment by DakotaNelson** [comment]
My thinking is that this would make adding new modules (especially if you don't have access to the main repo) easier - dependencies would be installed at runtime instead of requiring you to figure out dependencies yourself (since you couldn't add to requirements.txt yourself without write access to the main repo). Drop a file in the right folder and you're done.

That said, you're right that this us way too much work, especially at this point, and I don't plan on continuing work on this any time soon.
