### ISSUE TITLE
Echo Mode Non-Functional

### ISSUE THREAD

**Issue by ManickYoj** [DakotaNelson/sneaky-creeper#44]
Somewhere along the line, the echo command broke. Test command:
`echo "testing" | ./screep echo -e identity`

Should return the word `testing`, but instead errors out:
`File "./screep", line 202, in decode
    moduleName = '.'.join(['encoders', encoderName])
TypeError: sequence item 1: expected string, list found`

Digging into this, encoderName is coming into decode from echo as a list (`['identity']`) and needs to be stringified or, rather, should have already been extracted from a list in echo.

We need to be a bit more careful that our PRs don't break existing code. I'll dig into this one.

**Comment by DakotaNelson** [comment]
Aw, crap.

I merged PR #42 today, which includes some infrastructure for testing. We definitely need to start adding more tests so this sort of thing doesn't become commonplace.
