### ISSUE TITLE
Base94 encoder broke the Soundcloud Channel

### ISSUE THREAD

**Issue by byronwasti** [DakotaNelson/sneaky-creeper#50]
The soundcloud Channel does not interface well with the new base94 encoder system we have. I am not totally sure what it is trying to do and how to interface with it for the send/receive of data.

**Comment by DakotaNelson** [comment]
Look into the PR that has to do with packetization. B94 is used to prepend
a count of which packet this is, of total. This should be totally
transparent to channels.

**Comment by DakotaNelson** [comment]
@byronwasti is this still an issue?
