### ISSUE TITLE
AES encoder

### ISSUE THREAD

**Issue by davinerd** [DakotaNelson/sneaky-creeper#53]
Since it's impractical to use asymmetric encryption on large files, why not simply use AES ?

I can work on this too. Let me know if you like the idea and need help.

Thanks

**Comment by ManickYoj** [comment]
AES sounds like a fantastic idea, but I will note one issue that came up discussing this in past. Encryption in sneaky-creeper serves a somewhat different purpose than it does in other contexts.

The logic with asymmetric key in this case is less for establishing a shared symmetric key than it is that an attacker can send their public key embedded in sneaky-creeper to a target machine and then that machine can exfiltrate data that only the attacker can read.

Using symmetric key encryption requires the target machine to have a key (obviously) which can serve to decrypt sent data as well as send it.

That's not to say we shouldn't have it. In fact I'm fully behind using AES here and I think it is rather necessary. But we may want to note in the README or future documentation that using the AES module does make incident response on the target system easier by helping reveal what data has been successfully exfiltrated from a system.

**Comment by davinerd** [comment]
I don't think I've fully understand your point, so I apoligise if I did some mistake below.
I think your point also apply to both channels and encoders.

When doing incident response that involves law enforcement, it's easy for them to ask for a specific API key/token to the related provider to spot the attacker account (this shouldn't be a problem, by the way) knowing which data has been stolen (if you don't clear your tracks or did not in time, of course).

Also, following your logic, what's the difference between b64 and AES ? IMHO, nothing.

The point is not to avoid the victim to know which data has been exifltrated (and I can't see how they can find it out, btw), but to avoid detection, so you need to bypass the network IDS/IPS/monitoring in place.

I didn't understand what you mean by "make incident response on the target system easier by helping reveal what data has been successfully exfiltrated from a system." I'm not going to encrypt the data on disk and then send them, but encrypt it in memory and send it out.

At this point, why not create an encryptor class to encrypt sneaky-creeper API keys/tokens and decode it in memory? :) just to make incident response life harder.

**Comment by DakotaNelson** [comment]
I like the idea of AES.

You're both right, in different contexts: @ManickYoj is correct in that with AES, anyone investigating can grab the key from memory and decrypt anything sent. However, @davinerd is also right that AES obscures the data in transit - much like base64, but in a way that can't be easily decoded like base64 can.

I'd love to see an AES module, @davinerd - I'm excited to see a pull request (PR) from you! Feel free to contact myself (or any collaborators on this repo) if we can help at all. :)

**Comment by davinerd** [comment]
I spent some hours figuring it out what would be the best approach to this.
Based on this really good post (https://security.stackexchange.com/questions/27776/block-chaining-modes-to-avoid) the best solution would be AES in CTR mode.

Using pycryto (that seems to be the standard), implementing such a crypto mode is quite a mess.
So I implemented it easily with [scrypt](https://bitbucket.org/mhallin/py-scrypt/src).

Pro:
- really easy and small code
- strong encryption scheme validated and audited
- do not have to reinvent the wheel, making possible mistakes not handling cryptostuff correctly

Cons:
- including another external library
- encrypted data has 'scrypt' as marker at the beginning of the stream. While this spot our AES implementation, this isn't a real security concern IMHO

Is that ok for you? If yes, I can send the PR anytime.

If we don't want to use CTR, we can use CFB. This guy made an amazing code [here](https://bitbucket.org/brendanlong/python-encryption/src/1737e959fa307d84a5dcf96c4139b1d91a08b2e9/encryption.py?at=master) that we can reuse.

Let me know what you think.

**Comment by DakotaNelson** [comment]
To be honest, I don't think I'm actually too worried about cryptographic strength here. The key will be more-or-less readily available on the implant (the code on the client), and I think this module is more focused on evading deep packet inspection and the like, not a concentrated attack (you should use asymmetric crypto for that, in this case, since the client isn't "trusted" per se).

I would go ahead and pick whichever one is
- reasonably secure (any of the options you mentioned)
- easy to implement

We can also easily upgrade it later if priorities shift.

**Comment by davinerd** [comment]
Cool, done. So prior to submit the encoder, you should merge my pull request, since line 154 is crucial to the AES encoder to work.

I can submit the encoder anyway, but will not work without it.
Let me know how do you want to proceed.

Thanks

**Comment by DakotaNelson** [comment]
I just merged #54, so you should be good to go. Thanks!
