### ISSUE TITLE
Twitter channel

### ISSUE THREAD

**Issue by Beercow** [DakotaNelson/sneaky-creeper#58]
When using the twitter channel the following error ocures:

```
C:\Users\Downloads\sneaky-creeper-master\sneaky-creeper-master>echo "test" | python screep.py -v send -e identity -c twitter -p twitter.json
←[34m[*]←[m Pipeline: identity -> twitter
←[34m[*]←[m Sending 1 packet.
1 of 1
Traceback (most recent call last):
  File "screep.py", line 332, in <module>
    sendData(channelName, encoded, params[channelName])
  File "screep.py", line 234, in sendData
    chan.send(packet, params)
  File "C:\Users\220551\Downloads\sneaky-creeper-master\sneaky-creeper-master\ch
annels\twitter.py", line 44, in send
    twitter.update_status(status=tweet)
NameError: global name 'tweet' is not defined
```

If I change `twitter.update_status(status=tweet)` to `twitter.update_status(status=data)` it sends a tweet but instead of saying `test` the tweet says `a b test`

I have not found a way to retrieve the tweet either.

**Comment by DakotaNelson** [comment]
The output `a b test` is correct - the `a` and `b` are there to denote which packet this is, of the total. When receiving using screep on the other end, it will parse and remove these before outputting the result. (if you try sending more than 130 or so characters, it'll automatically send two Tweets).

That said, the rest of that bug sounds like a problem. I'll take a look at it ASAP. Thanks for letting me know!

As for retrieving the Tweet - have you tried `python screep.py -v receive-e identity -c twitter -p twitter.json`?
