### ISSUE TITLE
Specify configuration using JSON config files

### ISSUE THREAD

**Issue by DakotaNelson** [DakotaNelson/sneaky-creeper#6]
Right now, configuration has to be provided on the command line, and sometimes there are a ton of looooong parameters. Specifying using JSON would make sending/receiving easier due to easy reproduction of configuration on both ends, as well as an easy way to move configuration around.

**Comment by DakotaNelson** [comment]
Closed by #36.

**Comment by DakotaNelson** [comment]
Just kidding: JSON strings can be specified, but not files.

There's a hack: `echo "test" | ./screep receive -e b64 -c file -p $(cat file-config.json)`, but it's just that - a hack. It also throws an error if there are newlines in the JSON file.

Another thought - YAML might be nicer.

**Comment by ManickYoj** [comment]
Yeah, this is next on my list. YAML is a possibility. Can you give an example of what a YAML command string would look like? And are you suggesting this just for files or for parameter lists in general?

**Comment by DakotaNelson** [comment]
It's very pythonic: https://en.wikipedia.org/wiki/YAML

Basically, remove the quotes in JSON and replace them with indentation formatting and you've got it.

See [this SO answer](http://stackoverflow.com/a/20493276/3341026). The downside is that it's another pip package, which probably isn't worth it, unfortunately.

The larger problem is that right now our JSON can't contain newlines or it gets real sad, which means the files have to be nasty one-liners.
