### ISSUE TITLE
Optional configuration parameters

### ISSUE THREAD

**Issue by DakotaNelson** [DakotaNelson/sneaky-creeper#7]
Right now, all of the config parameters specified in channels and encoders are required; it'll error out if they're not all there. However, sometimes parameters might be optional, or have a default.

**Comment by davinerd** [comment]
we should working on this. What about `optionalParams` ?
Something like:

```
optionalParams = {
   'sending': {},
   'receiving': {}
}
```

Seems to me the most natural way to do that.

**Comment by DakotaNelson** [comment]
I agree. It seems natural to make it the same as the existing method.

Another way I thought of: what if the module has parameters that are required, but only if other parameters have certain values?

Imagine there was a zip file encoder, that could encrypt the zip files, or not, whether or not the user wanted to. Maybe there's a parameter called `encrypt`, and if it's true, the zip file is encrypted. There would be another parameter, `password`, that would not be required, _unless_ `encrypt = true`. (if you're not encrypting the file, you wouldn't need to specify a password for the file)

The best way I could think of to deal with that scenario is for each module to have a member function called `checkParams` that takes all of the parameters and makes sure they are valid. That way module writers could add their own logic to decide if the parameters are valid. However, that's another requirement for the module writer and makes printing error messages hard. Perhaps it's a good feature for the future when we run into the need, and for now we should go the simple route, like you suggested above.

**Comment by davinerd** [comment]
So this `checkParams` can be called by `Exfil` to check for parameters, but I think it's too "generic", while the approach of `requiredParams` and `optionalParams` seems reasonable to me, clean and easy to maintain.

Edit:
However, I saw we already have the `check_params()` in `modules.py`, but we don't use it (`exfil.py` still use the old checking method). We can leverage that, adding the `optionalParams` described above.

Of couse, modules writers can override that function and create their own version.

**Comment by davinerd** [comment]
trying to find a solution to this, it's not that easy. Here's what I came out with: 692c8cd1660316e2f5e9739d4440f6bbeef2eddf 
If you take a look at it, what I've done is basicaly:
- created a second param, called `optParams` (renaming the old `params` to `reqParams`
- moved the checking parameters function inside the `Modules` class
- converted only the `File` and `B64` classes to test

As that, if you are a module writer, you have to specify the optional parameters with a default value within the class code.
If you want to use our library, you can specify optional parameters or leave the default.

Is this make sense to you? If yes, I can start converting all our channels and encoders (while for the optional parameters I'd like to leave the implementation to each author).
