### ISSUE TITLE
Configuration Namespacing

### ISSUE THREAD

**Issue by DakotaNelson** [DakotaNelson/sneaky-creeper#8]
Right now, configuration parameters for all encoders and channels have no enforced uniqueness - if two encoders have a parameter named 'key,' using them together is not possible.

We need some way to make sure name collision will never occur between modules, with no control over the actual names (i.e. we don't know who will be writing these modules, and can't really control them, and this needs to work anyway).

Namespacing seems like a good answer to me (especially since module and encoder names must be unique), but there might be something better I haven't thought of.

**Comment by ManickYoj** [comment]
An edge case to watch out for - echoing an encoder with different parameters for encode and decode. I don't think this collides with what you're describing, if implemented well. 

EG - echo rsa with public and private key params (public for encode, private for decode)

**Comment by DakotaNelson** [comment]
Yeah, I ran into that yesterday. I just specified them both and it worked out - which is unwieldy, but I think works just fine.

You're right though, we'll have to look out for that.

I was thinking the namespacing would go something like:

`-p rsa:publicKey publickey.pem.pub` - where anything tagged `rsa:` would only be passed to that module.

That way, if someone else makes a module that needs a public key, they can still name the parameter whatever they want.

That makes parameters even _more_ verbose, but... I think we need something like it or we're going to run into collisions pretty soon.

**Comment by ManickYoj** [comment]
Can we not namespace off the preceding encoder? EG `-e rsa -p publicKey publickey.pub privateKey privatekey` ? It seems a bit more natural to me, but I have no problem with the explicit `rsa:` namespacing either.

**Comment by DakotaNelson** [comment]
The problem is that I don't think we can't detect the order of arguments like that as it stands. (And we probably wouldn't want to if we could -  I suspect that would confuse people like crazy. I haven't seen the order of flagged parameters matter anywhere else, and making up conventions like that is bad juju.)

I think the solution to this might lie in #6 - maybe we just shouldn't allow command line parameters at all? Or maybe they have to be specified as a long JSON string?

**Comment by ManickYoj** [comment]
I'm a fan of allowing a user to either use JSON-strings or a config file. So, for JSON strings, a good example would be `echo -e rsa -p {rsa: {publicKey: publickey.pub, privateKey: privatekey}}`, correct?

And the same format for config files?

**Comment by DakotaNelson** [comment]
Yep, exactly. I like it. And each encoder/channel gets its own dictionary of configuration parameters, so you only specify `-p` once and toss a giant blob into it.

**Comment by ManickYoj** [comment]
Alright. I'll take this one.

**Comment by DakotaNelson** [comment]
@ManickYoj how's progress on this?

**Comment by ManickYoj** [comment]
Poor. I've been working on other projects. I can unassign myself if someone else wants to take it. I still hope to get it done, but I haven't made any significant progress.
