### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by davinerd** [DakotaNelson/sneaky-creeper#81]
What if we start introducing version? Now that we created the library, it's a good idea to introduce the versioning concept. We can use the "Milestone" Github feature, and introduce the appropriate code sections.

I think we can start with version 1.0 by adding the following features:
- Channel attributes ( #71 )
- Filetype Adapter ( #69 )
- Dropbox Channel ( #52 )
- Github Channel ( #63 )
- Optional configuration parameters ( #7 )
- Subcommands description ( #14 )
- Can't handle plain messages ( #73 )

Then later, we can add some other features. Another thing to decide: subversioning goes up by 1 or by 5? i.e. 1.x branch has next subversion 1.1 or 1.5 (and then 1.2 or directly 2.0?).

**Comment by DakotaNelson** [comment]
I like the idea, but I'm not sure the added formality does anything for us. In your mind, what's the benefit for doing versioning? PyPI and packaging? (because that might be worth thinking about soon)

**Comment by davinerd** [comment]
It helps not only for packaging, but also to coordinate efforts, prioritize issues and PRs, so we can create a better tool in a timely manner.

**Comment by DakotaNelson** [comment]
Just created an 0.2 milestone, we can go ahead and keep making them as we define new goals.
