### ISSUE TITLE
set_channel_params Error Message Confusing

### ISSUE THREAD

**Issue by DakotaNelson** [DakotaNelson/sneaky-creeper#87]
```
channel = "file"
encoders = []

d = Exfil(channel, encoders)
```

Returns:

```
  File "implant.py", line 21, in setUpFeed
    feed.set_channel_params(channelParams)
  File "/home/dnelson/projects/multicat/sneaky-creeper/sneakers/exfil.py", line 40, in set_channel_params
    for k in params.keys():
AttributeError: 'str' object has no attribute 'keys'
```

Which is deeply unfortunate. It should be possible to specify an empty `encoders` list.

**Comment by DakotaNelson** [comment]
Whooooooooops, I completely miscategorized this.

The real issue is that `d.set_channel_params("")` returns the error above. Still, a useful error message would very likely improve some lives.

**Comment by davinerd** [comment]
this (e45d1bb) should do the trick.
