### ISSUE TITLE
Similar project

### ISSUE THREAD

**Issue by PaulSec** [DakotaNelson/sneaky-creeper#93]
Hello guys, 

I just came across your project and I've built something really similar called [DET (Data Exfiltration Toolkit)](https://github.com/sensepost/det) which does data exfiltration with multiple channel support. 
I just finished watching your talk and this is something you were looking at. 
I also have some PowerShell support which is extremely handy if the host does not have Python installed on the box.

I also saw that you were speaking about doing Twitter exfil using DM (and I am the guy who wrote [Twittor](https://github.com/PaulSec/twittor), some kind of backdoor using Twitter DMs). Seems the date of your post is similar to when I released Twittor, publicly. 

I don't know where is your project going right now (Last commit 5 months ago) but extremely interesting topic but I'd be extremely keen to integrate some of your channels in DET. 
Should be fine with your MIT license. 

Anyway, extremely interesting project and a pretty cool discovery I've just made. 

Keep it up!
Paul

**Comment by DakotaNelson** [comment]
Hey Paul - thanks for the note!

DET looks fantastic! I'll definitely do a close read of the code - thanks for sharing. I'm glad to finally meet the creator of Twittor - it's been a huge inspiration in making this project. (along with [Gcat](https://github.com/byt3bl33d3r/gcat))

As you've noticed, this project has been fairly quiet for a while - for better or worse, the development team is undergraduate students, so we tend to be short on free time to develop these sorts of side projects during the school year. I'd love to see some channels integrated into DET - I'm sure the various authors would appreciate credit of some sort, but we put the MIT license in place to encourage sharing, so do whatever you'd like! :smile: I'm hoping to continue work on this, although I've been telling myself that for a while.

Again - thanks for reaching out, and it's great to meet you! I'll be keeping a close eye on DET - keep in touch!

Dakota
